<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <OutputType>Library</OutputType>
    <GeneratePkgDefFile>true</GeneratePkgDefFile>
    <UseCodebase>true</UseCodebase>
    <IncludeAssemblyInVSIXContainer>true</IncludeAssemblyInVSIXContainer>
    <IncludeDebugSymbolsInVSIXContainer>false</IncludeDebugSymbolsInVSIXContainer>
    <IncludeDebugSymbolsInLocalVSIXDeployment>false</IncludeDebugSymbolsInLocalVSIXDeployment>
    <CopyBuildOutputToOutputDirectory>true</CopyBuildOutputToOutputDirectory>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.VisualStudio.SDK" Version="17.0.0" ExcludeAssets="runtime" NoWarn="NU1605" />
    <PackageReference Include="Microsoft.VSSDK.BuildTools" Version="17.0.5232" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="source.extension.cs" />
    <Compile Include="Guids.cs" />
    <Compile Include="PackageIds.cs" />
    <Compile Include="ToggleClrExceptionsPackage.cs" />
    <Compile Include="ToggleClrExceptionsCommand.cs" />
  </ItemGroup>

  <ItemGroup>
    <VSCTCompile Include="ToggleClrExceptions.vsct">
      <ResourceName>Menus.ctmenu</ResourceName>
    </VSCTCompile>
  </ItemGroup>

  <ItemGroup>
    <None Include="source.extension.vsixmanifest" />
  </ItemGroup>

</Project>
